### ISSUE TITLE
Website Naming

### ISSUE THREAD

**Issue by vivek-sundli** [vivek-sundli/swasthya#7]
Trim websites of their names
for eg: github.com to github

**Comment by urvishdevelops** [comment]
> Trim websites of their names for eg: github.com to github

Can you explain me more Vivek? I am getting difficulty in getting you

**Comment by vivek-sundli** [comment]
please go through the updated ReadMe.

you will find the website naming as shown 
![gfi](https://github.com/vivek-sundli/swasthya/assets/33592335/85f6e590-5f7e-4514-9965-934ec0ba2491)

triming the name from _github.com_ to _github_ is the requirement here
similarly for other websites as well.

**Comment by vivek-sundli** [comment]
Done
